name: route_guardian
description: A cybersecurity-styled personal safety routing app for Nigeria and Africa.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.1.0
  http: ^1.6.0
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  image_picker: ^1.0.7
  google_polyline_algorithm: ^3.1.0
  flutter_polyline_points: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
